// GENERATED by graph-build.mjs — do not hand-edit. Rebuilt by `node build.mjs` from the configured brain.
// 3 notes · 3 linked · 2 wiki links · 2026-09-16
export const BRAIN = {"notes":3,"nodes":[{"id":"index","g":"00-Meta","d":2,"x":0.224,"y":0.036},{"id":"2026-09-15 goal ship-usable-office-map","g":"00-Meta","d":1,"x":-0.255,"y":0.964},{"id":"2026-09-16 goal ship-brain-and-files-map","g":"00-Meta","d":1,"x":0.031,"y":-1}],"links":[[1,0],[2,0]],"floor":[[0.283,0.102],[-0.477,0.879],[0.195,-0.981]]};
