import type { ApiEnv } from "../platform/config/env.js";

/** In-memory API env for tests. Pass overrides for the setting under test. */
export function makeTestEnv(overrides: Partial<ApiEnv> = {}): ApiEnv {
  return {
    host: "127.0.0.1",
    port: 8787,
    logLevel: "error",
    corsOrigins: ["http://localhost:1420"],
    databaseUrl: undefined,
    dataDir: undefined,
    bedrockApiKey: "test-bedrock-key",
    bedrockRegion: "eu-north-1",
    bedrockModels: ["amazon.nova-lite-v1:0", "amazon.nova-pro-v1:0", "google.gemma-3-12b-it"],
    openRouterApiKey: undefined,
    openRouterModels: ["openai/gpt-4o-mini"],
    openAiApiKey: undefined,
    anthropicApiKey: undefined,
    xaiApiKey: undefined,
    defaultModel: "amazon.nova-lite-v1:0",
    primaryProviderId: "bedrock",
    publicBaseUrl: "http://127.0.0.1:8787",
    authWebUrl: undefined,
    siteUrl: "https://testingworkspace.arrabai.com",
    moyasarSecretKey: undefined,
    moyasarPublishableKey: undefined,
    dataEncryptionKey: undefined,
    releasesDir: "/tmp/arrab-releases-test",
    googleClientId: undefined,
    googleClientSecret: undefined,
    googleOAuthRedirectUri: undefined,
    microsoftClientId: undefined,
    microsoftClientSecret: undefined,
    microsoftOAuthRedirectUri: undefined,
    githubAppClientId: undefined,
    githubAppClientSecret: undefined,
    githubAppSlug: undefined,
    githubOAuthRedirectUri: undefined,
    gitlabClientId: undefined,
    gitlabClientSecret: undefined,
    gitlabOAuthRedirectUri: undefined,
    bitbucketClientId: undefined,
    bitbucketClientSecret: undefined,
    bitbucketOAuthRedirectUri: undefined,
    linearClientId: undefined,
    linearClientSecret: undefined,
    linearOAuthRedirectUri: undefined,
    slackClientId: undefined,
    slackClientSecret: undefined,
    slackOAuthRedirectUri: undefined,
    notionClientId: undefined,
    notionClientSecret: undefined,
    notionOAuthRedirectUri: undefined,
    whatsappWebhookVerifyToken: undefined,
    whatsappAppSecret: undefined,
    finnhubApiKey: undefined,
    finnhubWebhookSecret: undefined,
    whoopClientId: undefined,
    whoopClientSecret: undefined,
    whoopOAuthRedirectUri: undefined,
    fitbitClientId: undefined,
    fitbitClientSecret: undefined,
    fitbitOAuthRedirectUri: undefined,
    googleDriveClientId: undefined,
    googleDriveClientSecret: undefined,
    googleDriveOAuthRedirectUri: undefined,
    googleCalendarClientId: undefined,
    googleCalendarClientSecret: undefined,
    googleCalendarOAuthRedirectUri: undefined,
    figmaClientId: undefined,
    figmaClientSecret: undefined,
    figmaOAuthRedirectUri: undefined,
    openwaBaseUrl: "http://127.0.0.1:2785",
    openwaWebhookSecret: undefined,
    openwaSessionId: "arrab",
    openwaApiKey: undefined,
    trustProxy: false,
    apiRoutePrefix: "",
    ...overrides,
  };
}
